val githubProperties = java.util.Properties()
githubProperties.load(java.io.FileInputStream("$rootDir/github.properties"))

dependencyResolutionManagement {
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()

        jcenter() // Warning: this repository is going to shut down soon
         maven("https://jitpack.io")
        maven("https://artifactory.paytm.in/libs-release-local")
        maven("https://maven.juspay.in/jp-build-packages/hypersdk-asset-download/releases/")
        maven("https://maven.juspay.in/jp-build-packages/hyper-sdk/")
        maven("https://sdk.uxcam.com/android/")
        maven( "https://packages.bureau.id/api/packages/Bureau/maven")
        maven("https://plotline-android-sdk.s3.amazonaws.com")
        maven("https://plugins.gradle.org/m2/")
        maven("https://storage.googleapis.com/r8-releases/raw")
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/Changejarapp/REPOSITORY_NAME_HERE") // Replace REPOSITORY_NAME_HERE with actual GitHub repo name
            credentials {
                username = githubProperties.getProperty("gprUser") ?: System.getenv("GPR_USER")
                password = githubProperties.getProperty("gprKey") ?: System.getenv("GPR_API_KEY")
            }
        }
    }

    pluginManagement {
        repositories {
            gradlePluginPortal()
            mavenCentral()
            google()
        }
    }
}
rootProject.name = "JarApp"
include("app")
include(":base")
include(":core-ui")
include(":core-utils")
include(":core-compose-ui")
include(":core-image-picker")
include(":core-web-pdf-viewer")
include(":feature-payment")
include(":feature-user-api")
include(":feature-daily-investment")
include(":feature-homepage")
include(":feature-profile")
include(":feature-settings")
include(":feature-sell-gold")
include(":feature-gold-price-alerts")
include(":feature-buy-gold-v2")
include(":feature-spin")
include(":feature-kyc")
include(":feature-vasooli")
include(":feature-transaction")
include(":feature-transaction-common")
include(":feature-gifting")
include(":feature-lending-kyc")
include(":feature-refer-earn-v2")
include(":feature-jar-duo")
include(":feature-round-off")
include(":feature-mandate-payment")
include(":feature-mandate-payment-common")
include(":feature-gold-sip")
include(":feature-quests")
include(":feature-weekly-magic")
include(":feature-weekly-magic-common")
include(":feature-lending")
include(":feature-gold-delivery")
include(":feature-gold-redemption")
include(":feature-savings-common")
include(":feature-gold-lease")
include(":feature-post-setup")
include(":feature-in-app-review")
include(":feature-spends-tracker")
include(":feature-sms-sync")
include(":feature-contacts-sync-common")
include(":shared")
include(":shared:core-preferences")
include(":shared:core-analytics")
include(":shared:core-remote-config")
include(":shared:core-network")
include(":shared:core-base")
include(":shared:feature-user-api")
include(":shared:feature-weekly-magic")
include(":shared:feature-weekly-magic-common")
include(":shared:feature-settings")
include(":shared:feature-gifting")
include(":shared:feature-one-time-payments")
include(":shared:feature-one-time-payments-common")
include(":shared:feature-gold-price")
include(":shared:feature-gold-price-alerts")
include(":shared:feature-quests")
include(":shared:feature-gold-redemption")
include(":shared:feature-sell-gold")
include(":shared:feature-refer-earn-v2")
include(":shared:feature-round-off")
include(":shared:feature-profile")
include(":shared:feature-post-setup")
include(":shared:feature-onboarding")
include(":shared:feature-gold-sip")
include(":shared:feature-gold-delivery")
include(":shared:feature-homepage")
include(":shared:core-logger")
include(":shared:feature-in-app-notification")
include(":shared:feature-spends-tracker")
include(":shared:feature-transaction-common")
include(":shared:feature-transaction")
include(":shared:feature-sell-gold-common")
include(":shared:feature-buy-gold-v2")
include(":feature-daily-investment-cancellation")
include(":shared:feature-daily-investment-cancellation")
include(":feature-health-insurance")
include(":shared:feature-health-insurance")
include(":shared:feature-lending")
include(":shared:feature-lending-kyc")
include(":shared:feature-kyc")
include(":feature-goal-based-saving")
include(":shared:feature-goal-based-saving")
include(":shared:feature-mandate-payments-common")
include(":shared:feature-jar-duo")
include(":shared:feature-contact-sync-common")
include(":shared:feature-spin")
include(":shared:feature-coupon-api")
include(":shared:feature-gold-lease")
include(":shared:feature-daily-investment")
include(":shared:feature-savings-common")
include(":feature-in-app-stories")
include(":shared:feature-story")
include(":feature-promo-code")
include(":shared:feature-promo-code")
include(":feature-graph-manual-buy")
include(":shared:feature-graph-manual-buy")
include(":feature-exit-survey")
include(":feature-calculator")
include(":shared:feature-calculator")
include(":shared:feature-exit-survey")
