package com.jar.app.feature_health_insurance.shared.domain.events

object HealthInsuranceEvents {



    //events
    const val Insurance_LandingPageShown = "Insurance_LandingPageShown"
    const val Insurance_Select_Members_Shown = "Insurance_SelectMembersShown"
    const val Insurance_Select_Plan_Shown = "Insurance_SelectPlanShown"
    const val Insurance_BenefitsShown = "Insurance_BenefitsShown"
    const val Insurance_BenefitsClicked = "Insurance_BenefitsClicked"
    const val Get_InsuredClicked = "Get_InsuredClicked"
    const val Get_InsuredShown = "Get_InsuredShown"
    const val Insurance_Need_Help_Clicked = "Insurance_NeedHelpClicked"
    const val Insurance_FAQClicked = "Insurance_FAQClicked"
    const val FAQ_Clicked = "FAQ_Clicked"
    const val Back_ButtonClicked = "Back_ButtonClicked"
    const val Leaving_InsuranceShown = "Leaving_InsuranceShown"
    const val Plan_Benefits_Clicked = "View_BenefitsClicked"
    const val Leaving_CTAClicked = "Leaving_CTAClicked"
    const val Member_Clicked = "Member_Clicked"
    const val Insurance_EldestAgeEntered = "Insurance_EldestAgeEntered"
    const val Good_HealthDecClicked = "Good_HealthDecClicked"
    const val Next_InsuranceDetailsClicked = "Next_InsuranceDetailsClicked"
    const val Insurance_PlanClicked = "Insurance_PlanClicked"
    const val Payment_TypeClicked = "Payment_TypeClicked"
    const val Health_Insurance_Event = "Health_Insurance_Events"
    const val Health_Insurance_Event_Ts = "Health_Insurance_Events_Ts"
    const val Clicked_InsuranceLanding_Top_Video = "Clicked_InsuranceLanding_Top_Video"
    const val Clicked_InsuranceLanding_carousel_Video = "Clicked_InsuranceLanding_carousel_Video"
    const val Health_Insurance_PaymentBSScreenShown = "Health_Insurance_PaymentBSScreenShown"
    const val Health_Insurance_PaymentBSScreenClicked = "Health_Insurance_PaymentBSScreenClicked"
    const val Insurance_Manage_Screen_Clicked = "Insurance_ManageScreenClicked"
    const val Insurance_ManageScreen_Shown = "Insurance_ManageScreenShown"
    const val Pay_NowClicked = "Pay_NowClicked"
    const val View_BenefitsClicked = "View_BenefitsClicked"
    const val Insurance_PaymentShown = "Insurance_PaymentShown"
    const val Insurance_PaymentClicked = "Insurance_PaymentClicked"
    const val UPI_Transition_ScreenShown = "UPI_Transition_ScreenShown"
    const val Insurance_SuccessShown = "Insurance_SuccessShown"

    //properties
    const val FromScreen = "FromScreen"
    const val Type = "Type"
    const val Tab = "Tab"
    const val Button = "Button"
    const val Member = "Member"
    const val Age = "Age"
    const val Plan = "Plan"
    const val Payment_type = "Payment_type"
    const val Amount = "Amount"
    const val Status = "Status"
    const val ThumbNailText = "Thumbnail_text"
    const val Add_Member_Details = "Add_Member_Details"
    const val TRANSACTION_DETAILS = "transaction_details"
    const val ADULT_CNT = "adultCnt"
    const val KID_CNT = "kidCnt"
    const val SCROLL_POSITION = "scroll_position"
    const val EVENT_NAME = "EventName"
    const val ORDER_ID = "OrderID"
    const val Payment_Frequency = "Payment_Frequency"
    const val Insurance_Status = "InsuranceStatus"
    const val Premium_Payment_Status = "PremiumPaymentStatus"
    const val Insured_Type = "InsuredType"
    const val Vertical_Card_Position = "VerticalCardPosition"
    const val Identity_Verification_Status = "IdentityVerificationStatus"
    const val Vertical_Card_Title = "VerticalCardTitle"
    const val Base_Plan = "BasePlan"
    const val Policy_Start_Date = "PolicyStartDate"
    const val Policy_End_Date = "PolicyEndDate"
    const val Members_Insured = "MembersInsured"
    const val Premium_Due_Date = "PremiumDueDate"
    const val Premium_Amount = "PremiumAmount"
    const val CTA_Clicked = "CTAClicked"
    const val AUTO_PAYMENT_STATUS = "AutoPaymentStatus"
    const val GRACE_PERIOD_STATUS = "Graceperiodstatus"
    const val PREPAID_UI = "prepaidUpi"
    const val PREPAID_UPI_APP = "prepaidupiapp"
    const val UPI_CLICKED = "UPi_Clicked"
    const val PAY_NOW_NEW = "Pay_Now_New"
    const val NUMBER_OF_AVAILABLE_UPI_APP = "number_of_available_upi"
    const val PRE_SELECTED_UPI = "pre_selected_upi"
    const val SELECTED_UPI = "selected_upi"
    const val BUTTON_TYPE = "button_type"

    const val BUTTON_TYPE_UPI_APP = "UpiApp"
    const val BUTTON_TYPE_PROCEED = "Proceed"
    const val BUTTON_TYPE_CANCEL = "Cancel"
    //values
    const val Insurance_landing_page = "Insurance landing page"
    const val Member_Spouse = "Spouse"
    const val Member_Kid1 = "Kid1"
    const val Member_Kid2 = "Kid2"
    const val Post_Purchase = "Post Purchase"
    const val Health_Insurance = "Health Insurance"
    const val Plan_Details = "Plan Details"
    const val MANDATE_BACK_CLICKED = "MANDATE_BACK_CLICKED"
    const val INSURANCE_ACTIVE = "Active"
    const val INSURANCE_EXPIRED = "Expired"
    const val SUCCESSFUL = "Successful"
    const val FAILED = "Failed"
    const val YES = "Yes"
    const val NO = "No"
    const val SINGLE_PERSON = "Single Person"
    const val MULTIPLE_PERSON = "Multiple Person"
    const val PREPAID_UI_TRUE = "True"
    const val PREPAID_UI_FALSE = "False"
    const val PREPAID_UPI_APP_GPAY = "Gpay"
    const val PREPAID_UPI_APP_PHONEPE = "Phonepe"
    const val PREPAID_UPI_APP_PAYTM = "Paytm"
    const val PAYMENT_TYPE_MANUAL = "Manual"
    const val PAYMENT_TYPE_MANDATE_SETUP = "Mandate setup"

}