package com.jar.app.feature_spin.shared.util

object SpinsEventKeys {
    const val ShownSpinTheWheelScreen = "ShownSpinTheWheelScreen"
    const val FeatureTypeSpinAndWin = "spin_and_win"
    const val ScreenTypeSpinAndWin = "spin_and_win"
    const val PulledSpinlever = "PulledSpinlever"
    const val PullFull = "full"
    const val PullHalf = "half"
    const val ShownSpinRewardsScreen = "ShownSpinRewardsScreen"
    const val ScreenWinnings = "winnings"
    const val ScreenJackpotJar = "Jackpot_Jar"
    const val ScreenJackpotOtherBrands = "Jackpot_OtherBrand"
    const val ClickedButtonRewardsScreen = "ClickedButtonRewardsScreen"
    const val FeatureType = "FeatureType"
    const val CTA = "CTA"
    const val Close = "Close"
    const val ShownDailySpinsOverScreen = "Shown_daily_spins_over_screen"
    const val daily_spin_count = "daily_spin_count!"
    const val todays_winnings = "todays_winnings"
    const val total_winnings = "total_winnings"
    const val ClickedButtonDailySpinsOverScreen = "Clicked_button_daily_spins_over_screen"
    const val Back = "Back"
    const val Shown_HowtoUseWinningsScreen = "Shown_HowtoUseWinningsScreen"
    const val Clicked_button_HowtoUseWinningsScreen = "Clicked_button_HowtoUseWinningsScreen"
    const val UseWinnings = "Use Winnings"
    const val Brand = "Brand"
    const val Coupon = "Coupon"
    const val Share = "Share"
    const val Cross = "Cross"
    const val Title = "Title"
    const val Shown_HowtoPlayScreen = "Shown_HowtoPlayScreen"
    const val Clicked_Button_HowtoPlayScreen = "Clicked_Button_HowtoPlayScreen"

    //Events, Params and Values for Quest Flow in Spins
    const val button_type = "button_type"
    const val spins_left = "spins_left"
    const val lever = "lever"
    const val Shown_QuestSpinsPage = "Shown_QuestSpinsPage"
    const val Clicked_QuestSpinsPage = "Clicked_QuestSpinsPage"
}