package com.jar.app.feature_daily_investment_cancellation.impl.util

object DailyInvestmentCancellationEventKey {
    const val DSCancellation_StopDSpopupClicked = "DSCancellation_StopDSpopupClicked"
    const val DSCancellation_StopDSpopupShown = "DSCancellation_StopDSpopupShown"
    const val DSCancellation_PauseDSpopupShown = "DSCancellation_PauseDSpopupShown"
    const val DSCancellation_PageLaunched = "DSCancellation_PageLaunched"
    const val DSCancellation_PageClicked = "DSCancellation_PageClicked"
    const val DSCancellation_PauseDSpopupClicked = "DSCancellation_PauseDSpopupClicked"
    const val Shown_Success_PauseDailySavingsPopUp = "Shown_Success_PauseDailySavingsPopUp"
    const val DSCancellation_StopDSpopup_Clicked = "DSCancellation_StopDSpopup_Clicked"
    const val Shown_Success_DisableDailySavingsPopUp = "Shown_Success_DisableDailySavingsPopUp"
    const val DSCancellation_StopDSSuccessScreenClicked = "DSCancellation_StopDSSuccessScreenClicked"
    const val Button_type = "Button_type"
    const val Stop_Now = "Stop Now"
    const val Stop_Icon = "Stop Icon"
    const val Infinite = "Infinite"
    const val Paused = "Paused"
    const val Disabled = "Disabled"
    const val Stop_Type = "Stop Type"
    const val No_of_days = "No_of_days"
    const val Withdraw_Icon = "Withdraw Icon"
    const val Gold_Delivery_Icon = "Gold Delivery Icon"
    const val isbottomreached = "isbottomreached"
    const val Shown_Success_DailySavingsResumedScreen = "Shown_Success_DailySavingsResumedScreen"
}

object DailyInvestmentCancellationKey {
    const val From_screen = "From_screen"
    const val DailyInvestmentSettingsV2 = "DailyInvestmentSettingsV2"
    const val State = "State"
    const val Total_Amount_saved = "Total_Amount_saved"
    const val Current_payment_platform = "Current_payment_platform"
    const val DS_Mandate_Amount = "DS_Mandate_Amount"
}

object DailyInvestmentPauseKey {
    const val Pause_Type = "Pause_Type"
    const val No_of_days = "No_of_days"
    const val Final_selected_days = "Final_pause_days"
    const val Final_paused_days = "Final_paused_days"
    const val is_calendar_used = "is_calendar_used"
}

object DailyInvestmentStopKey {
    const val type = "type"
}

object DailyInvestmentStatusScreen {
    const val DSCancellation_ErrorStateDSSetupShown = "DSCancellation_ErrorStateDSSetupShown"
    const val DSCancellation_ErrorStateDSSetupClicked = "DSCancellation_ErrorStateDSSetupClicked"
    const val is_Permanently_Cancel_flow = "is_Permanently_Cancel_flow"
    const val Source = "Source"
    const val Error_Type = "Error Type"
    const val Knowledge = "Knowledge"
    const val Statistic = "Statistic"
    const val V2Stop = "V2Stop"
    const val Pause = "Pause"
    const val Stop = "Stop"
    const val None = "None"
    const val Failed = "Failed"
    const val In_Progress = "In Progress"
    const val button_type = "button_type"
    const val Retry ="Retry"
    const val Notify_me ="Notify Me"
    const val Back ="Back"
    const val Close ="Close"
    const val Disabled ="Disabled"
    const val Setup_Now_Banner ="Setup Now Banner"
    const val Setup_Now_Cta ="Setup Now CTA"
    const val FAQ ="FAQ"
    const val Settings ="Settings"
    const val Resume_Now_Banner ="Resume Now Banner"
    const val Restart_Now_Banner ="Restart Daily Savings Banner"
    const val Resume_Now ="Resume Now"
    const val Track_Your_Savings ="Track your Savings"
    const val Stop_Daily_Savings ="Stop Daily Savings"
    const val Pause_Daily_Savings ="Pause Daily Savings"
    const val Resume_Now_CTA ="Resume Now CTA"
    const val Restart_Now_CTA ="Restart Now CTA"
    const val Change_Amount ="Update Amount CTA"
    const val Day ="Day"
    const val Permanent ="Permanent"
    const val Cancellation_Page = "Cancellation Page"
    const val Date ="Date"
    const val Pause_Now ="Pause Now"
    const val Save_Weekly ="Save Weekly"
    const val Buy_Gold ="Buy Gold"
    const val Go_To_Home ="Go to Home"
}