package com.jar.app.feature_post_setup.util

object PostSetupEventKey {

    //Params
    const val cal_month_success_days_count = "cal_month_success_days_count"
    const val cal_month_success_amount = "cal_month_success_amount"
    const val cal_month_inprogress_days_count = "cal_month_inprogress_days_count"

    const val cal_month_inprogress_amount = "cal_month_inprogress_amount"
    const val cal_month_failed_days_count = "cal_month_failed_days_count"
    const val cal_month_failed_amount = "cal_month_failed_amount"
    const val active_days_count = "active_days_count"
    const val is_current_month = "is_current_month"
    const val current_month = "current_month"
    const val calender_month = "calender_month"
    const val current_date = "current_date"
    const val button_type = "button_type"
    const val day_state = "day_state"
    const val faq_title = "faq_title"
    const val feature_type = "feature_type"
    const val back = "back"
    const val help = "help"
    const val FAQ = "FAQ"
    const val Calendar_date = "Calendar_date"
    const val DS_education_icon = "DS_education_icon"
    const val action = "action"
    const val duration = "duration"
    const val active = "active"
    const val multiple_failures = "multiple_failures"
    const val first_time = "first_time"
    const val shown = "shown"
    const val close = "close"
    const val paused = "paused"
    const val disabled = "disabled"
    const val resume_now = "resume_now"
    const val resolve_now = "resolve_now"
    const val setup_now = "setup_now"
    const val failed_days = "failed_days"
    const val is_selected = "is_selected"
    const val selected_days_count = "selected_days_count"
    const val pre_selected_days_count = "pre_selected_days_count"
    const val deselected_days_count = "deselected_days_count"
    const val final_selected_days_count = "final_selected_days_count"
    const val total_savings = "total_savings"
    const val daily_savings_spins = "daily_savings_spins"
    const val post_setup_screen_state = "post_setup_screen_state"
    const val post_setup_daily_savings = "post_setup_daily_savings"

    //Events
    const val PostSetupDS_ScreenLaunched = "PostSetupDS_ScreenLaunched"
    const val PostSetupDS_SaveNowClicked = "PostSetupDS_SaveNowClicked"
    const val PostSetupDS_CalenderMonthChanged = "PostSetupDS_CalenderMonthChanged"
    const val PostSetupDS_ScreenClicked = "PostSetupDS_ScreenClicked"
    const val PostSetupDS_FAQsClicked = "PostSetupDS_FAQsClicked"
    const val Shown_PauseScreen_DSSettings = "Shown_PauseScreen_DSSettings"
    const val PostSetupDS_ScreenBottomReached = "PostSetupDS_ScreenBottomReached"
    const val PostSetupDS_ClearAmountScreenLaunched = "PostSetupDS_ClearAmountScreenLaunched"
    const val PostSetupDS_ClearAmountPaymentClicked = "PostSetupDS_ClearAmountPaymentClicked"
    const val PostSetupDS_ManageMySavingsClicked = "PostSetupDS_ManageMySavingsClicked"
    const val PostSetupDS_PurchaseStatusScreenShown = "PostSetupDS_PurchaseStatusScreenShown"
    const val PostSetupDS_PurchaseStatusScreenClicked = "PostSetupDS_PurchaseStatusScreenClicked"
    const val PostSetupDS_ViewInvoiceClicked = "PostSetupDS_ViewInvoiceClicked"
}