package com.jar.app.core_preferences.util

internal object PrefConstants {
    const val USER_INVITE_LINK = "USER_INVITE_LINK"

    const val INVITE_LINK_EXPIRY = "INVITE_LINK_EXPIRY"

    const val APPSFLYER_REFERRAL_USER_ID = "APPSFLYER_REFERRAL_USER_ID"

    const val DEFAULT_APP_VERSION = 203

    const val IS_ONBOARDING_COMPLETE = "IS_ONBOARDING_COMPLETE"

    const val AUTH_TYPE = "AUTH_TYPE"

    const val ACCESS_TOKEN = "ACCESS_TOKEN"

    const val IS_ONBOARDING_SHOWN = "IS_ONBOARDING_SHOWN"

    const val NEW_ONBOARDING_STATE = "NEW_ONBOARDING_STATE"

    const val OLD_ONBOARDING_STATE = "OLD_ONBOARDING_STATE"

    const val REFRESH_TOKEN = "REFRESH_TOKEN"

    const val JAR_SHIELD_ENABLED = "JAR_SHIELD_ENABLED"

    const val REMOTE_CONFIG_FORCE_REFRESH_KEY = "REMOTE_CONFIG_FORCE_REFRESH_KEY"

    const val IS_REMOTE_CONFIG_FETCHED = "IS_REMOTE_CONFIG_FETCHED"

    const val IS_REMOTE_CONFIG_EVENT_SENT = "IS_REMOTE_CONFIG_EVENT_SENT"

    const val IS_SMS_PROCESSING_ENABLED = "IS_SMS_PROCESSING_ENABLED"

    const val IS_DAILY_SAVING_CROSS_PROMOTION_COMPLETED =
        "IS_DAILY_SAVING_CROSS_PROMOTION_COMPLETED"

    const val IS_AUTOPAY_CROSS_PROMOTION_COMPLETED = "IS_AUTOPAY_CROSS_PROMOTION_COMPLETED"

    const val IS_FIRST_AUTOPAY_DISABLED = "is_first_autopay_disabled"

    const val LAST_SURVEY_CONSUMED = "LAST_SURVEY_CONSUMED"

    const val FIRST_INVESTMENT_EVENT_SENT = "first_investment_event_sent"

    const val APP_VERSION = "APP_VERSION"

    const val HAS_SHOWN_GOLD_PRICE_ALERT_ONCE = "HAS_SHOWN_GOLD_PRICE_ALERT_ONCE"

    const val GOLD_PRICE_ALERT = "gold_price_alert"

    const val SHOWN_RATING_DIALOG_COUNT = "SHOWN_RATING_DIALOG_COUNT"

    const val FIRST_SUCCESSFUL_INVESTMENT = "first_successful_investment"

    const val USER_KEY = "USER_KEY"

    const val FCM_TOKEN = "FCM_TOKEN"

    const val SHOW_TRANSACTION_OVERLAY = "show_txn_overlay"

    const val SHOW_TRANSACTION_DETAIL_OVERLAY = "show_txn_detail_overlay"

    const val HAS_SHOWN_AUTO_SAVE_VIDEO = "HAS_SHOWN_AUTO_SAVE_VIDEO"

    const val SHOULD_SYNC_APPSFLYER_ATTRIBUTION_DATA = "sync_appsflyer_attribution_data"

    const val IS_FIRST_SESSION = "IS_FIRST_SESSION"

    const val SHOULD_SHOW_VASOOLI_INTRO = "SHOULD_SHOW_VASOOLI_INTRO"

    const val HAS_SHOWN_ONBOARDING_CONGRATS_SCREEN = "HAS_SHOWN_ONBOARDING_CONGRATS_SCREEN"

    const val USER_PHONE_NUMBER = "USER_PHONE_NUMBER"

    const val USER_NAME = "USER_NAME"

    const val PRIMARY_UPI_ID = "PRIMARY_UPI_ID"

    const val SHOULD_SHOW_DUO_ONBOARDING_SCREEN = "SHOULD_SHOW_DUO_ONBOARDING_SCREEN"

    const val HAS_SHOWN_CUSTOMISED_ONBOARDING = "HAS_SHOWN_CUSTOMISED_ONBOARDING"

    const val HAS_SHOWN_DIGITAL_COIN_INTRO = "HAS_SHOWN_DIGITAL_COIN_INTRO"

    const val IS_DIWALI_CAMPAIGN_RUNNING = "IS_DIWALI_CAMPAIGN_RUNNING"

    const val MYSTERY_CARD_COUNT = "MYSTERY_CARD_COUNT"

    const val MYSTERY_CARD_CHALLENGE_ID = "MYSTERY_CARD_CHALLENGE_ID"

    const val USER_LIFE_CYCLE_MANDATE = "USER_LIFE_CYCLE_MANDATE"

    const val SELECTED_LANGUAGE_CODE = "SELECTED_LANGUAGE_CODE"

    const val SELECTED_LANGUAGE_NAME = "SELECTED_LANGUAGE_NAME"

    const val DEFAULT_LANGUAGE_CODE = "en"

    const val DEFAULT_LANGUAGE_NAME = "English"

    const val PUSH_NOTIFICATION_CONTEXT = "context"

    const val IS_NEW_USER_CHECK_EVENT_FIRED = "IS_NEW_USER_CHECK_EVENT_FIRED"

    const val SHOW_HOME_VERTICAL_OVERLAY = "SHOW_HOME_VERTICAL_OVERLAY"

    const val IS_ON_DEMAND_SMS_SENT = "IS_ON_DEMAND_SMS_SENT_V2"

    const val HAS_SHOWN_CONTACT_PERMISSION_HOME_SCREEN = "HAS_SHOWN_CONTACT_PERMISSION_HOME_SCREEN"

    const val DUO_STORY_VIEW_COUNT = "DUO_STORY_VIEW_COUNT"

    const val AUTOMATICALLY_DAILY_SAVING_EDUCATION_SCREEN_SHOWN = "AUTOMATICALLY_DAILY_SAVING_EDUCATION_SCREEN_SHOWN"

    const val HOW_TO_USE_WINNINGS = "HOW_TO_USE_WINNINGS"

    const val SPIN_V2_INTRO_SHOWN = "SPIN_V2_INTRO_SHOWN"

    const val SPIN_ALERT_NUDGE = "SPIN_ALERT_NUDGE"

    const val SHOULD_ANIMATE_TYPE_ONE_EPOXY_MODEL = "SHOULD_ANIMATE_TYPE_ONE_EPOXY_MODEL"

    const val SHOULD_ANIMATE_TYPE_TWO_EPOXY_MODEL = "SHOULD_ANIMATE_TYPE_TWO_EPOXY_MODEL"

    const val SHOULD_SHOW_POST_SETUP_SCREEN_FOR_NEW_SETUP = "SHOULD_SHOW_POST_SETUP_SCREEN_FOR_NEW_SETUP"

    const val HAS_CLEARED_PREFERENCES_FOR_MIGRATION = "HAS_CLEARED_PREFERENCES_FOR_MIGRATION"

    const val DAILY_INVESTMENT_CANCELLATION_V2_DATE = "DAILY_INVESTMENT_CANCELLATION_V2_DATE"

    const val IS_GOLD_LEASE_LANDING_ANIMATION_SHOW = "IS_GOLD_LEASE_LANDING_ANIMATION_SHOW"

    const val SHOW_CONGRATS_CARD_IN_QUESTS = "SHOW_CONGRATS_CARD_IN_QUESTS"

    const val IS_APP_WALKTHROUGH_SHOWN_TO_USER = "IS_APP_WALKTHROUGH_SHOWN_TO_USER"

    const val SHOULD_SHOW_APP_WALKTHROUGH_TO_USER = "SHOULD_SHOW_APP_WALKTHROUGH_TO_USER"

    const val API_BASE_URL = "API_BASE_URL"

    const val IS_AUTOMATION_ENABLED = "IS_AUTOMATION_ENABLED"

    const val SHOULD_SHOW_SPLASH_SCREEN = "SHOULD_SHOW_SPLASH_SCREEN"

}