package com.jar.app.feature_homepage.shared.domain.model

enum class FeatureFlag {
    REFER_AND_EARN,
    GOLD_DELIVERY,
    PROMO_CODE,
    GIFT_GOLD,
    BUY_GOLD,
    ROUNDOFF,
    READY_CASH,
    COUPON_CODE_DISCOVERY,
    SIP_CARD,
    UPDATE_DS,
    DUO,
    VASOOLI,
    HELP_SECTION,
    PRENOTIFICATION,
    SPENDS_TRACKER,
    HEALTH_INSURANCE,
    GOLD_LEASE_V2,
    HEALTH_INSURANCE_SINGLE_CARD_HOMEFEED,
    DAILY_SAVINGS_V3,
    DS_UPDATE_JOURNEY
}