package com.jar.app.feature_round_off.shared.util

object RoundOffEventKey {


    //ROUND OFF
    const val no = "no"
    const val yes = "yes"
    const val currentState = "currentState"
    const val currentAmount = "currentAmount"
    const val amount = "amount"
    const val days = "days"
    const val finalState = "finalState"
    const val Shown_RoundOffScreen = "Shown_RoundOffScreen"
    const val Clicked_DisableToggle_RoundOffScreen = "Clicked_DisableToggle_RoundOffScreen"
    const val Shown_DisableRoundOffPopUp = "Shown_DisableRoundOffPopUp"
    const val Clicked_Pause_DisableRoundOffPopUp = "Clicked_Pause_DisableRoundOffPopUp"
    const val Clicked_Disable_DisableRoundOffPopUp = "Clicked_Disable_DisableRoundOffPopUp"
    const val Shown_Success_DisableRoundOffPopUp = "Shown_Success_DisableRoundOffPopUp"
    const val Clicked_EnableToggle_RoundOffScreen = "Clicked_EnableToggle_RoundOffScreen"
    const val Clicked_EditAmount_RoundOffScreen = "Clicked_EditAmount_RoundOffScreen"
    const val Shown_SetRoundOffPopUp = "Shown_SetRoundOffPopUp"
    const val Clicked_SetRoundOff_RoundOffPopUp = "Clicked_SetRoundOff_RoundOffPopUp"
    const val Clicked_Cancel_RoundOffPopUp = "Clicked_Cancel_RoundOffPopUp"
    const val Shown_Success_RoundOffPopUp = "Shown_Success_RoundOffPopUp"
    const val Clicked_Pause_RoundOffScreen = "Clicked_Pause_RoundOffScreen"
    const val Shown_Success_RoundOffResumedScreen = "Shown_Success_RoundOffResumedScreen"
    const val Shown_PauseRoundOffPopUp = "Shown_PauseRoundOffPopUp"
    const val Clicked_Pause_PauseRoundOffPopUp = "Clicked_Pause_PauseRoundOffPopUp"
    const val Clicked_Cancel_PauseRoundOffPopUp = "Clicked_Cancel_PauseRoundOffPopUp"
    const val Shown_Success_PauseRoundOffPopUp = "Shown_Success_PauseRoundOffPopUp"
    const val Clicked_Invest10_RoundOffScreen = "Clicked_Invest10_RoundOffScreen"
    const val Roundoff_AutosaveActivated_Screenshown = "Roundoff_AutosaveActivated_Screenshown"
    const val Roundoff_AutosaveActivatedFromDetails_Screenshown = "Roundoff_AutosaveActivatedFromDetails_Screenshown"

    //Round off -Autopay setup flow
    //params
    const val SourceFlow = "sourceFlow"
    const val Action = "Action"
    const val Shown = "Shown"
    const val Confirm = "Confirm"
    const val SkipClicked = "SkipClicked"
    const val RetryClicked = "RetryClicked"
    const val RefreshClicked = "RefreshClicked"
    const val View_Transaction = "View Transaction"
    const val Hide_Transaction = "Hide Transaction"
    const val SaveNowClicked = "SaveNowClicked"
    const val ActiveSavingsShown = "activeSavingsShown"
    const val DailySavingsAmount = "dailySavingsAmount"
    const val MandateAmount = "mandateAmount"
    const val PaymentPreference = "PaymentPreference"
    const val Autopay = "Autopay"
    const val Manual = "Manual"
    const val OkayClicked = "OkayClicked"
    const val CrossClicked = "CrossClicked"
    const val IsSpendsDetected = "IsSpendsDetected"
    const val RoundoffAmount = "RoundoffAmount"
    const val YesAllowClicked = "YesAllowClicked"
    const val GoToHomeClicked = "GoToHomeClicked"
    const val AutomateNowClicked = "AutomateNowClicked"
    const val DownloadInvoiceClicked = "DownloadInvoiceClicked"
    const val ContactSupportClicked = "ContactSupportClicked"

    //Events
    const val AutomaticRoundoff_Invest10 = "AutomaticRoundoff_Invest10"
    const val Clicked_back_AutopayMandate = "Clicked_back_AutopayMandate"
    const val Shown_AutopayMandate = "Shown_AutopayMandate"
    const val Clicked_Proceed_AutopayMandateScreen = "Clicked_Proceed_AutopayMandateScreen"
    const val AutomaticRoundoff_SuccessScreen = "AutomaticRoundoff_SuccessScreen"
    const val AutomaticRoundoff_FailureScreen = "AutomaticRoundoff_FailureScreen"
    const val AutomaticRoundoff_PendingScreen = "AutomaticRoundoff_PendingScreen"
    const val ManualRoundoff_SuccessScreen = "ManualRoundoff_SuccessScreen"
    const val ManualRoundoff_FailureScreen = "ManualRoundoff_FailureScreen"
    const val ManualRoundoff_PendingScreen = "ManualRoundoff_PendingScreen"

    const val Roundoff_Education_Screen = "Roundoff_Education_Screen"
    const val Roundoff_Detection_Screen = "Roundoff_Detection_Screen"
    const val Roundoff_Detection_Screen_Ts = "Roundoff_Detection_Screen_Ts"
    const val Roundoff_PaymentMethod_Screen = "Roundoff_PaymentMethod_Screen"
    const val RoundOff_ManualPaymentActivated_Screen = "RoundOff_ManualPaymentActivated_Screen"

    const val CurrentStatus = "CurrentStatus"
    const val Status = "Status"
    const val CTA = "CTA"
    const val Back = "Back"
    const val Cancel = "Cancel"
    const val AutoSave10Enabled = "AutoSave10Enabled"
    const val AutopayUPI = "AutopayUPI"
    const val BankAccount = "BankAccount"
    const val MandateRequired = "MandateRequired"
    const val UpdatedAutoSave10 = "UpdatedAutoSave10"
    const val ManualPaymentMethod = "ManualPaymentMethod"
    const val StopRoundoff = "StopRoundoff"
    const val DisableAutoSave = "DisableAutoSave"
    const val PaymentType = "PaymentType"
    const val PauseDuration = "PauseDuration"
    const val Pause = "Pause"
    const val Disable = "Disable"

    const val Shown_IntermediaryScreen_RoundoffSettingsScreen =
        "Shown_IntermediaryScreen_RoundoffSettingsScreen"
    const val Shown_Automatic_RoundoffSettingsScreen = "Shown_Automatic_RoundoffSettingsScreen"
    const val Shown_Manual_RoundoffSettingsScreen = "Shown_Manual_RoundoffSettingsScreen"
    const val Clicked_manualPayemnt_AutomaticRoundoffSettingsScreen =
        "Clicked_manualPayemnt_AutomaticRoundoffSettingsScreen"
    const val Clicked_AutomaticPayemnt_ManualRoundoffSettingsScreen =
        "Clicked_AutomaticPayemnt_ManualRoundoffSettingsScreen"
    const val Shown_StopScreen_RoundoffSettings = "Shown_StopScreen_RoundoffSettings"
    const val Shown_PauseScreen_RoundoffSettings = "Shown_PauseScreen_RoundoffSettings"
    const val Shown_StopConfirmation_RoundoffSettings = "Shown_StopConfirmation_RoundoffSettings"
    const val Shown_RoundoffSettings_PausedStateScreen = "Shown_RoundoffSettings_PausedStateScreen"
    const val Shown_RoundOff_Settings_Screen_Ts = "Shown_RoundOff_Settings_Screen_Ts"
}