object Dependencies {

    object Common {
        const val gradleVersion = "7.2.2"
        const val kotlinVersion = "1.8.21"
        const val coroutine_version = "1.7.3"
        const val core_analytics_version = "0.0.8"
        const val kermit_version = "1.2.2"
        const val core_network_client_version = "1.2.7"
        const val core_remote_config = "1.0.6"
        const val ktor_version = "2.3.3"
        const val kotlin_serialization = "1.4.1"
        const val core_preferences = "0.0.8"
        const val build_config = "0.13.3"
        const val moko_parcelize = "0.8.0"
        const val moko_resource = "0.23.0"
        const val kmm_bridge = "0.3.7"
        const val kotlin_bignum = "0.3.8"
        const val core_kmm_flow = "0.0.2"
        const val core_paging_version = "0.6.7"
        const val kotlin_datetime_version = "0.4.0"
        const val sqldelight_version = "1.5.5"
        const val firebase_pref = "1.4.2"
    }

    object Android {
        const val otp_pin_view = "2.1.2"
        const val camerax_version = "1.1.0"
        const val hyperSdkVersion = "1.0.4"
        const val crashlyticsVersion = "2.9.2"
        const val firebaseAppDistributionVersion = "3.2.0"
        const val googleServices = "4.3.15"
        const val nav_version = "2.5.2"
        const val hilt_version = "2.46.1"
        const val junit_version = "4.13.2"
        const val android_junit_version = "1.1.3"
        const val esperesso_version = "3.4.0"
        const val core_ktx_version = "1.8.0"
        const val app_compat_version = "1.5.1"
        const val glide_version = "4.13.2"
        const val permission_version = "4.9.2"
        const val leak_canary_version = "2.8.1"
        const val lifecycle_version = "2.5.1"
        const val room_version = "2.5.2"
        const val work_version = "2.7.1"
        const val timber_version = "5.0.1"
        const val eventbus_version = "3.3.1"
        const val preferences_version = "1.2.0"
        const val threetenbp_version = "1.6.0"
        const val firebase_version = "31.4.0"
        const val paging_version = "3.1.1"
        const val material_version = "1.6.1"
        const val material_design = "1.1.1"
        const val recycler_view_version = "1.2.1"
        const val constraint_layout_version = "2.1.4"
        const val fragment_ktx_version = "1.5.2"
        const val progress_hud_version = "1.2.0"
        const val overscroll_version = "1.1.1"
        const val amplitude_version = "3.35.1"
        const val clevertap_version = "4.6.6"
        const val userexperior_version = "7.2.4"
        const val appsflyer_version = "6.12.2"
        const val facebook_sdk_version = "16.2.0"
        const val paytm_sdk_version = "1.6.16"
        const val juspay_sdk_version = "2.1.13"
        const val expandable_view_version = "2.9.2"
        const val lottie_version = "6.0.0"
        const val shimmer_version = "0.5.0"
        const val adapter_delegate_version = "4.3.2"
        const val circular_progress_bar_version = "3.1.0"
        const val epoxy_version = "5.0.0-beta05"
        const val swipe_refresh_version = "1.1.0"
        const val smart_refresh_layout_version = "2.0.6"
        const val flex_box_version = "3.0.0"
        const val phone_number_utils_version = "8.12.47"
        const val country_code_picker_version = "2.4.2"
        const val exo_player_version = "2.18.0"
        const val hilt_navigation = "1.0.0"
        const val mockk_version = "1.9.2"
        const val truth_version = "1.1.3"
        const val android_arch_core_testing = "2.1.0"
        const val google_places = "2.6.0"
        const val truecaller_version = "2.7.0"
        const val androidx_browser = "1.4.0"
        const val android_mp_chart = "v3.1.0"
        const val tinder_state_machine = "0.3.0"
        const val androidx_install_referrer = "2.2"
        const val play_services_ads = "21.2.0"
        const val play_services_auth = "20.4.1"
        const val play_services_auth_api_phone = "18.0.1"
        const val luban = "1.1.8"
        const val simple_rating_bar = ""
        const val hilt_worker = "1.0.0"
        const val androidx_legacy_support = "1.0.0"
        const val kotlinx_coroutines_play_services = "1.6.4"
        const val mlkit_face_detection = "17.1.0"
        const val flip_view_version = "3.0.3"
        const val androidx_biometric_version = "1.2.0-alpha04"
        const val contacts_util_version = "0.2.3"
        const val auto_starter_version = "1.1.0"
        const val intuit = "1.1.0"

        const val plotline_version = "3.3.6"
        const val play_app_update = "2.0.1"
        const val play_services_basement = "18.2.0"

        /* Compose libraries */
        const val compose_bom_version = "2023.05.01"
        const val compose_paging_version = "3.2.0-rc01"
        const val compose_glide_version = "1.0.0-alpha.3"
        const val compose_onebone_toolbar = "2.3.5"
        const val compose_kotlin_compiler_version = "1.4.7"
        const val compose_lottie = "6.0.0"
        const val compose_showkase = "1.0.0-beta17"
        const val compose_paging = "1.0.0-alpha20"
        const val compose_coil = "2.4.0"
        const val skydoves_balloon_version = "1.5.2"
        const val accompanist_version = "0.30.1"
        const val compose_ui_text = "1.4.3"

        const val compose_flowlayout = "0.29.1-alpha"
        const val lifecycle_viewmodel_compose = "2.6.1"

        //ripple effect
        const val ripple_effect_library = "1.0.1"
        const val exo_player_dependency = "1.1.1"

        //Bureau SDK
        const val bureau_sdk_version = "2.1.1"

        //R8 (For adding support sealed classes because of Bureau SDK)
        const val r8_version = "8.2.24"

    }
}
