package com.jar.app.feature_homepage.shared.util

object EventKey {

    const val COUPON_CODE = "couponCode"
    const val PageName = "PageName"

    const val Shown_HomeScreen = "Shown_HomeScreen"
    const val CashbackBannerShown = "CashbackBannerShown"
    const val SinglePageHomeFeed = "SinglePageHomeFeed"
    const val experimentName = "experimentName"
    const val experiment_status = "experiment_status"
    const val variant_type = "variant_type"

    const val Shown_HomeScreenCard = "Shown_HomeScreenCard"
    const val Shown_HomeScreenCard_Ts = "Shown_HomeScreenCard_Ts"
    const val Clicked_HomeScreenCard = "Clicked_HomeScreenCard"
    const val Shown_CongratsFirstLocker = "Shown_CongratsFirstLocker"
    const val Clicked_EndIcon_HomeScreenCard = "Clicked_EndIcon_HomeScreenCard"
    const val Clicked_CouponCard_homefeed = "Clicked_CouponCard_homefeed"

    const val CLICKED_BUY_GOLD_HOME_FAB = "ClickedBuyGoldFloatingButton_HomeScreen"
    const val ClickedKeepInvesting_GamificationHomeScreen =
        "ClickedKeepInvesting_GamificationHomeScreen"
    const val ClickedDashboardMoreinfo_HomeScreen = "ClickedDashboardMoreinfo_HomeScreen"

    const val Clicked_Button_LoanCard = "Clicked_Button_LoanCard"

    const val Clicked_UpdateDS_HomeScreen = "Clicked_UpdateDS_HomeScreen"
    const val HomePage_Clicked_PayNowGoldSip = "HomePage_Clicked_PayNowGoldSip"
    const val Action = "Action"
    const val ButtonType = "Button Type"
    const val Next = "Next"
    const val Amount = "Amount"
    const val SipType = "SipType"
    const val Selected_DS_amount = "Selected DS amount"
    const val Current_DS_amount = "Current DS amount"
    const val Slider_moved = "Slider moved"
    const val Save_Now_clicked = "Save Now clicked"
    const val ShownFirstCoinCard = "Shown_FirstCoin_Card"
    const val ShownFirstCoinCardTs = "Shown_FirstCoin_Card_Ts"
    const val Track_my_order = "Track my order"
    const val Delivery_Failure = "Delivery Failure"
    const val Delivery_Success = "Delivery Success"
    const val OKAY = "OKAY"
    const val Contact_Support = "Contact Support"
    const val Cross = "Cross"
    const val Get_it_Delivered = "Get it Delivered"
    const val autopay_setup = "autopay_setup"
    const val gold_savings_available = "gold_savings_available"
    const val Clicked_FirstCoin_Card = "Clicked_FirstCoin_Card"
    const val First_coin_card = "First_coin_card"
    const val See_Details = "See Details"
    const val Introduction_Screen = "Introduction Screen"
    const val Back = "Back"
    const val Proceed = "Proceed"
    const val Landing_page = "Landing page"
    const val Active = "Active"
    const val NonActive = "NonActive"
    const val Setup_Daily_Savings = "Setup Daily Savings"
    const val Buy_More_Gold = "Buy More Gold"
    const val savings_gold_amount = "savings_gold_amount"
    const val autopay_amount = "autopay_amount"
    const val screen_type = "screen_type"
    const val Success_percentage = "Success_percentage"
    const val process_status = "process_status"
    const val Get_it_delivered = "Get it delivered"
    const val needed_gold_amount = "needed_gold_amount"
    const val success_percentage ="success_percentage"
    const val Shown_CreditConsent = "Shown_CreditConsent_bottomsheet_onboarding"
    const val FromScreen = "FromScreen"
    const val Contact_Refreshed = "Contact_Refreshed"
    const val Clickedinfo_Investroundoff = "Clickedinfo_Investroundoff"
    const val Appwalkthrough_shown = "Appwalkthrough_shown"
    const val Step = "Step"
    const val Skip = "Skip"
    const val Feature_Type = "FeatureType"
    const val Cta_Text = "Cta_text"
    const val Button_Type = "Button"
    const val Shown_Hc_Sticky_Event = "Shown_HC_Sticky"
    const val Clicked_HC_Sticky = "Clicked_HC_Sticky"
    const val Resume = "Resume"
    const val Cancel = "Cancel"

}