package com.jar.app.feature_gold_sip.shared.util

object GoldSipEventKey {

    //Params
    const val Action = "Action"
    const val FromScreen = "FromScreen"
    const val FromFlow = "FromFlow"
    const val Shown = "Shown"
    const val Resume = "Resume"
    const val CTA_clicked = "CTA Clicked"
    const val Back_Clicked = "Back Clicked"
    const val Slider_Moved = "Slider Moved"
    const val Sip_Type_Clicked = "Sip_Type_Clicked"
    const val AmountEntered = "AmountEntered"
    const val ClickedProceed = "ClickedProceed"
    const val Frequency = "Frequency"
    const val DefaultFrequency = "DefaultFrequency"
    const val Weekly = "Weekly"
    const val Monthly = "Monthly"
    const val SIP_Amount = "SIP amount"
    const val SIP_Date = "SIP date"
    const val Cross = "Cross"
    const val Cancel = "Cancel"
    const val Confirm = "Confirm"
    const val SetupFlow = "SetupFlow"
    const val UpdateFlow = "UpdateFlow"
    const val WeekDaySelected = "WeekDaySelected"
    const val DateSelected = "DateSelected"
    const val SetupStatus = "SetupStatus"
    const val SIPStatus = "SIPStatus"
    const val ChangeAmount = "ChangeAmount"
    const val Setup = "Setup"
    const val Refresh = "Refresh"
    const val Retry = "Retry"
    const val Back = "Back"
    const val Update = "Update"
    const val Disable = "Disable"
    const val Pause = "Pause"
    const val Homepage = "Homepage"
    const val Onboarding = "Onboarding"
    const val GoBackToSettings = "GoBackToSettings"
    const val AutopayUPI = "AutopayUPI"
    const val BankAccount = "BankAccount"
    const val Contact_Support = "Contact Support"
    const val FeatureCardClicked = "FeatureCardClicked"

    //Events
    const val Shown_SIPEducationScreen = "Shown_SIPEducationScreen"
    const val Shown_SIPsetupScreen = "Shown_SIPsetupScreen"
    const val Shown_PaymentDayBottomSheet = "Shown_PaymentDayBottomSheet"
    const val Shown_SIP_PostSetupScreen = "Shown_SIP_PostSetupScreen"
    const val Shown_IntermediaryScreen_SIPsettings = "Shown_IntermediaryScreen_SIPsettings"
    const val Shown_SIPSettingsScreen = "Shown_SIPSettingsScreen"
    const val Shown_UpdateSIPbottomSheet = "Shown_UpdateSIPbottomSheet"
    const val Shown_SIPUpdatedSuccessfully = "Shown_SIPUpdatedSuccessfully"
    const val Shown_StopSIPBottomSheet = "Shown_StopSIPBottomSheet"
    const val Shown_SIP_PauseStatus = "Shown_SIP_PauseStatus"
    const val Shown_SIP_DisableStatus = "Shown_SIP_DisableStatus"
    const val Shown_PauseSIPBottomSheet = "Shown_PauseSIPBottomSheet"
    const val Clicked_Button_Skip = "Clicked_Button_Skip"
}