package com.jar.app.feature_homepage.shared.domain.event.detected_spends

import com.jar.app.feature_round_off.shared.domain.model.InitiateDetectedRoundOffsPaymentRequest

data class ManualPaymentStepsShownEvent(val initiateDetectedRoundOffsPaymentRequest: InitiateDetectedRoundOffsPaymentRequest)