package com.jar.app.feature_jar_duo.shared.util

object DuoEventKey {

    const val Cancel_sync="Cancel_Sync"
    const val SCREEN = "Screen"
    const val CTA = "CTA"
    const val SECTION = "Section"
    const val Key = "Key"


    const val Shown_Screen_Duo = "Shown_Screen_Duo"
    const val Duo_Screen_Name = " Duo Main Page"
    const val Clicked_button_Duo = "Clicked_button_Duo"
    const val Clicked_button_Duo_main_page = "Clicked_button_Duo Main Page"
    const val introduction = "introduction"
    const val Create_first_duo = "Create first duo"
    const val duo_list = "duo list"
    const val Invitation = "Invitation"
    const val Duo_details = "Duo details"
    const val rename_duo = "rename duo"
    const val rename = "Rename"
    const val delete = "Delete"

    const val share_invite = "share invite"
    const val delete_duo = "delete_duo"
    const val Card = "Card"
    const val New_duo = "New_duo"
    const val Accept_invite = "Accept invite"
    const val Reject_invite = "Reject invite"
    const val share_info = "share info"
    const val back = "back"
    const val option = "option"
    const val what_is_jar_duo = "what is jar duo"
    const val duo_info = "duo info"
    const val Button = "Button"
    const val FromScreen = "FromScreen"
    const val createFirstDuoScreen = "Create First Duo Screen"
    const val AutoSaveSelf = "AutoSaveSelf"
    const val DailySavingsSelf = "DailySavingsSelf"
    const val RoundOffFriend = "Round-off friend"
    const val RoundOffSelf = "Round-off self"
    const val KYCSelf = "KYC self"
    const val KYCFriend = "KYC Friend"
    const val AutoSaveFriend = "AutoSaveFriend"
    const val DailySavingsFriend = "DailySavingsFriend"
    const val InitialStatus = "InitialStatus"
    const val ContactList = "ContactList"
    const val GiveContactPermission = "GiveContactPermission"
    const val Invite_duo = "Invite_duo"
    const val BUY_MORE = "Buy more"
    const val SPIN_NOW = "Spin Now"
    const val SCREEN_INTRO = "Introduction"
    const val SCREEN_CONTACT_ACCESS = "Screen=Contact access"
    const val SCREEN_CONTACT_SYNC_SUCCESS = "Screen= Contacts sync success"
    const val SCREEN_DUO_HOMEPAGE = "Duo Home page"
    const val SCREEN_DUO_SENT_INVITE = "Sent Invites"
    const val SCREEN_DUO_PENDING_INVITE = "Pending Invites"
    const val Clicked_button_Duo_Introduction = "Clicked_button_Duo Introduction"
    const val Clicked_button_Duo_contact_access = "Clicked_button_Duo contact access"
    const val Clicked_button_New_Duo = "Clicked_button_New_Duo"
    const val Clicked_button_Duo_Home_page = "Clicked_button_Duo Home page"
    const val Skip = "Skip"
    const val Proceed = "Proceed"
    const val Replay = "Replay intro"
    const val ALLOW_ACCESS = "Allow access"
    const val ILL_DO_IT_LATER = "I’ll Do later"
    const val SINGLE_INVITE = "Single Invite"
    const val MULTIPLE_INVITE = "Multiple Invite"
    const val Sent_Invites = "sent Invites"
    const val Remind = "Remind"
    const val SELECT_ALL = "Select All"
    const val VIEW_ALL = "View All"
    const val Sync_contacts = "Sync contacts"
    const val Invite_friends = "Invite friends"
    const val Your_Duos = "Your Duos"
    const val Rename = "Rename"
    const val Delete = "Delete"
    const val Open = "Open"
    const val Top_banner = "Top banner"
    const val DUO_INVITES = "Duo Invites"
    const val Search = "Search"

}