package com.jar.app.feature_lending.shared.domain

object LendingEventKeyV2 {
    /**Props**/
    const val amount = "amount"
    const val entry_type = "entry_type"
    const val emp_type_selected = "emp_type_selected"
    const val company_name = "company_name"
    const val salary = "salary"
    const val pincode = "pincode"
    const val email = "email"
    const val changed_from = "changed_from"
    const val changed_to = "changed_to"
    const val tenure = "tenure"
    const val roi = "roi"
    const val emi_per_month = "emi_per_month"
    const val action = "action"
    const val bank_details_screen_shown = "bank_details_screen_shown"
    const val bank_details_screen_continue_clicked = "bank_details_screen_continue_clicked"
    const val faq_title = "faq_title"
    const val shown = "shown"
    const val shown_pending = "shown_pending"
    const val NEW_SELL_GOLD_FLOW = "NEW_SELL_GOLD_FLOW"
    const val continue_clicked = "continue_clicked"
    const val change_details_clicked = "change_details_clicked"
    const val selected_automation_mode = "selected_automation_mode"
    const val proceed_clicked = "proceed_clicked"
    const val enter_otp_screen_show = "enter_otp_screen_show"
    const val verify_otp_clicked = "verify_otp_clicked"
    const val time_out = "Time Out"
    const val error_type = "error_type"
    const val error_message = "error_message"
    const val ready_cash_needed_for = "ready_cash_needed_for"
    const val screen_name = "screen_name"
    const val lenderName = "lender_name"
    const val screen_type = "screen_type"
    const val user_action_on_previous_card = "user_action_on_previous_card"
    const val intro_screen = "intro_screen"
    const val p_details_screen = "p_details_screen"
    const val amount_screen = "amount_screen"
    const val emi_screen = "emi_screen"
    const val summary_screen = "summary_screen"
    const val bank_screen = "bank_screen"
    const val confirm_bank_screen = "confirm_bank_screen"
    const val consent_screen = "consent_screen"
    const val agreement_screen = "agreement_screen"
    const val loan_status = "loan_status"
    const val loan_id = "loan_id"
    const val source = "source"
    const val last_emi_number = "last_emi_number"
    const val upcoming_emi_number = "upcoming_emi_number"
    const val emi_number = "emi_number"
    const val emi_amount = "emi_amount"
    const val loan_amount = "loan_amount"
    const val screen_title = "screen_title"
    const val screen_text = "screen_text"
    const val last_emi_status = "last_emi_status"
    const val failed_emi_count = "failed_emi_count"
    const val emi_count = "emi_count"
    const val upcoming_emi_status = "upcoming_emi_status"
    const val payment_status = "payment_status"
    const val txn_status = "txn_status"
    const val button_type = "button_type"
    const val cancel = "cancel"
    const val button_status = "button_status"
    const val button_title = "button_title"
    const val credit_limit_status = "credit_limit_status"
    const val paid_loan_amount = "paid_loan_amount"
    const val available_cash_limit = "available_cash_limit"
    const val ready_cash_name = "ready_cash_name"
    const val user_type = "user_type"
    const val bank_details = "bank_details"
    const val View_Details = "View_Details"
    const val Contact_Support = "Contact_Support"
    const val Copied = "Copied"
    const val Transactions_ID_copied = "Transaction_ID_copied"
    const val Overview_Screen = "Overview_Screen"
    const val Payment_Status_Screen = "EMI Transaction Details Screen"
    const val Emi_Txn_Tab_Screen = "Emi_Txn_Tab_Screen"
    const val Emi_Details_Screen = "Emi_Details_Screen"
    const val Transactions_Screen = "Transactions_Screen"
    const val Transactions_Id = "Transaction_Id"
    const val field_name = "field_name"
    const val isFromRepeatWithdrawal = "isFromRepeatWithdrawal"
    const val isFromRepayment = "isFromRepayment"
    const val status = "status"
    const val right = "right"
    const val wrong = "wrong"
    const val text_displayed = "text_displayed"
    const val bank_statement_count = "BANK_STATEMENT_COUNT"
    const val details_confirmed = "details_confirmed"
    const val details_denied = "details_denied"
    const val consent_text_clicked = "consent_text_clicked"
    const val consent_text = "consent_text"
    const val scrolled = "scrolled"
    const val lender = lenderName
    const val url = "url"
    const val dismissed = "dismissed"
    const val account_selected = "account_selected"
    const val verifying_screen_shown = "verifying_screen_shown"
    const val redirecting_screen_shown = "redirecting_screen_shown"
    const val mandate_failure_screen_shown = "mandate_failure_screen_shown"

    //Screens
    const val EMPLOYMENT_SCREEN = "EMPLOYMENT_SCREEN"
    const val AMOUNT_SCREEN = "AMOUNT_SCREEN"
    const val EMI_SCREEN = "EMI_SCREEN"
    const val BANK_SCREEN = "BANK_SCREEN"
    const val SUMMARY_SCREEN = "SUMMARY_SCREEN"
    const val CONSENT_SCREEN = "CONSENT_SCREEN"
    const val AGREEMENT_SCREEN = "AGREEMENT_SCREEN"
    const val DISBURSAL_SCREEN = "DISBURSAL_SCREEN"
    const val INTRO_SCREEN = "INTRO_SCREEN"

    /**Events**/
    const val Lending_WithdrawalApplyRCashButtonClicked =
        "Lending_WithdrawalApplyRCashButtonClicked"
    const val Shown_HomeScreenCard = "Shown_HomeScreenCard"
    const val Clicked_HomeScreenCard = "Clicked_HomeScreenCard"
    const val Lending_PDetailsFirstScreenLaunched = "Lending_PDetailsFirstScreenLaunched"
    const val Lending_PDetailsCheckCreditLimitClicked = "Lending_PDetailsCheckCreditLimitClicked"
    const val Lending_PDetailsMainScreenLaunched = "Lending_PDetailsMainScreenLaunched"
    const val Lending_PDetailsEmpTypeSelected = "Lending_PDetailsEmpTypeSelected"
    const val Lending_PDetailsEmailPopUpLaunched = "Lending_PDetailsEmailPopUpLaunched"
    const val Lending_PDetailsCompNameAdded = "Lending_PDetailsCompNameAdded"
    const val Lending_PDetailsSalaryAdded = "Lending_PDetailsSalaryAdded"
    const val Lending_PDetailsErrorScreen = "Lending_PDetailsErrorScreen"
    const val Lending_PDetailsPinCodeAdded = "Lending_PDetailsPinCodeAdded"
    const val Lending_PDetailsMainScreenContinueClicked =
        "Lending_PDetailsMainScreenContinueClicked"
    const val Lending_RCashScreenShown = "Lending_RCashScreenShown"
    const val Lending_RCashAmountScreenShown = "Lending_RCashAmountScreenShown"
    const val Lending_RCashAmountTyped = "Lending_RCashAmountTyped"
    const val Lending_RCashAmountBarScrolled = "Lending_RCashAmountBarScrolled"
    const val Lending_RCashAmountContinueClicked = "Lending_RCashAmountContinueClicked"
    const val Lending_RCashEMIScreenLaunched = "Lending_RCashEMIScreenLaunched"
    const val Lending_RCashEMITenureSelected = "Lending_RCashEMITenureSelected"
    const val Lending_RCashEMIScreenConfirmClicked = "Lending_RCashEMIScreenConfirmClicked"
    const val Lending_eKYCRecordsFound = "Lending_eKYCRecordsFound"
    const val Lending_eKYCRecordsScreenShown = "Lending_eKYCRecordsScreenShown"
    const val Lending_eKYCScreenConfirmClicked = "Lending_eKYCScreenConfirmClicked"
    const val Lending_eKYCVerificationSuccessful = "Lending_eKYCVerificationSuccessful"
    const val Lending_ConfirmCkycDetailsLaunched = "Lending_ConfirmCkycDetailsLaunched"
    const val Lending_eKYCRecordsNotFound = "Lending_eKYCRecordsNotFound"
    const val Lending_BankDetailsScreenLaunched = "Lending_BankDetailsScreenLaunched"
    const val Lending_ReviewBankDetailsBSShown = "Lending_ReviewBankDetailsBSShown"
    const val Lending_PennydropVerificationScreenShown = "Lending_PennydropVerificationScreenShown"
    const val Lending_SummaryScreenShown = "Lending_SummaryScreenShown"
    const val Lending_SummaryScreenAction = "Lending_SummaryScreenAction"
    const val Lending_SummaryScreenProceedClicked = "Lending_SummaryScreenProceedClicked"
    const val Lending_SummaryAndAgreementScreenConfirmClicked = "Lending_SummaryAndAgreementScreenConfirmClicked"
    const val Lending_SummaryScreenSetupEMIClicked = "Lending_SummaryScreenSetupEMIClicked"
    const val Lending_EMISetupSuccessful = "Lending_EMISetupSuccessful"
    const val Lending_MandateTransitionScreens = "Lending_MandateTransitionScreens"
    const val Lending_LoanAmountScreenShown = "Lending_LoanAmountScreenShown"
    const val Lending_LoanAgreementScreenShown = "Lending_LoanAgreementScreenShown"
    const val Lending_LoanAgreementError = "Lending_LoanAgreementError"
    const val Lending_LoanApplicationSuccessfulScreenShown =
        "Lending_LoanApplicationSuccessfulScreenShown"
    const val Lending_NameUrRCashScreenShown = "Lending_NameUrRCashScreenShown"
    const val Lending_NameUrReadyCashScreenSaveClicked = "Lending_NameUrReadyCashScreenSaveClicked"
    const val Lending_YourLoanApproved = "Lending_YourLoanApproved"
    const val Lending_BackButtonClicked = "Lending_BackButtonClicked"
    const val Lending_MandateBackButtonClicked = "Lending_MandateBackButtonClicked"
    const val Lending_MandateNextPageLoad = "Lending_MandateNextPageLoad"
    const val Lending_CrossButtonClicked = "Lending_CrossButtonClicked"
    const val Lending_NeedHelpButtonClicked = "Lending_NeedHelpButtonClicked"
    const val Lending_I_WillDoItLaterButtonClicked = "Lending_CrossButtonClicked"
    const val Repay_BackButtonClicked = "Repay_BackButtonClicked"
    const val Lending_ApplicationRejected = "Lending_ApplicationRejected"
    const val Lending_ApplicationPennyDropCallbackPending =
        "Lending_ApplicationPennyDropCallbackPending"
    const val Landing_RejectionScreenShown = "Landing_RejectionScreenShown"
    const val Lending_RejectionScreenFAQClicked = "Lending_RejectionScreenFAQClicked"
    const val Lending_RejectionScreenGoHomeButtonClicked =
        "Lending_RejectionScreenGoHomeButtonClicked"
    const val Lending_FlowOpen = "Lending_FlowOpen"
    const val Lending_ABFLWaitingScreen = "Lending_ABFLWaitingScreen"

    //Foreclosure events
    const val Lending_ForeclosureDisabled = "Lending_ForeclosureDisabled"
    const val Lending_ForeclosureLoanScreenShown = "Lending_ForeclosureLoanScreenShown"
    const val Lending_ForeclosureLoanClicked = "Lending_ForeclosureLoanClicked"
    const val Lending_ForeclosureSummaryShown = "Lending_ForeclosureSummaryShown"
    const val Lending_ForeclosureMakePaymentClicked = "Lending_ForeclosureMakePaymentClicked"
    const val Lending_ForeclosureSuccessfulScreenShown = "Lending_ForeclosureSuccessfulScreenShown"
    const val Lending_ForeclosureSuccessfulScreenClicked =
        "Lending_ForeclosureSuccessfulScreenClicked"
    const val Lending_ForeclosedloanScreenShown = "Lending_ForeclosedloanScreenShown"
    const val Lending_ForeclosedloanScreenContactUsClicked =
        "Lending_ForeclosedloanScreenContactUsClicked"
    const val Lending_ForeclosurePaymentFailedScreenShown =
        "Lending_ForeclosurePaymentFailedScreenShown"
    const val Lending_ForeclosurePaymentFailedScreenClicked =
        "Lending_ForeclosurePaymentFailedScreenClicked"
    const val Lending_ForeclosurePaymentPendingScreenShown =
        "Lending_ForeclosurePaymentPendingScreenShown"
    const val Lending_ForeclosurePaymentPendingScreenClicked =
        "Lending_ForeclosurePaymentPendingScreenClicked"

    //Repayment
    const val Repay_LoanOverviewScreenLauched = "Repay_LoanOverviewScreenLauched"
    const val Repay_OverviewScreenMakePaymentClicked = "Repay_OverviewScreenMakePaymentClicked"
    const val Repay_OverviewScreenEMIDetailsClicked = "Repay_OverviewScreenEMIDetailsClicked"
    const val Repay_OverviewScreenForeClosureClicked = "Repay_OverviewScreenForeClosureClicked"
    const val Repay_OverviewScreenReadyCashDetailsClicked =
        "Repay_OverviewScreenReadyCashDetailsClicked"
    const val Repay_OverviewScreenChargesnFeesClicked = "Repay_OverviewScreenChargesnFeesClicked"
    const val Repay_PostPaymentScreenLaunched = "Repay_PostPaymentScreenLaunched"
    const val Repay_PostPaymentScreenClicked = "Repay_PostPaymentScreenClicked"

    //Repeat withdrawal
    const val Lending_RepeatWHomeScreenLaunched = "Lending_RepeatWHomeScreenLaunched"
    const val Lending_RepeatWHomeScreenReadyCashClicked =
        "Lending_RepeatWHomeScreenReadyCashClicked"
    const val Lending_RepeatWHomeScreenNeedSupportClicked =
        "Lending_RepeatWHomeScreenNeedSupportClicked"
    const val Lending_RepeatWHomeScreenLoanEMIClicked = "Lending_RepeatWHomeScreenLoanEMIClicked"
    const val Lending_RCashNeedHelpClicked = "Lending_RCashNeedHelpClicked"
    const val Lending_RCashEMIConfirmClicked = "Lending_RCashEMIConfirmClicked"
    const val Lending_RCashEMINeedHelpClicked = "Lending_RCashEMINeedHelpClicked"
    const val Lending_RCashEMIScreenScrolled = "Lending_RCashEMIScreenScrolled"
    const val Lending_RepeatWBankDetailScreenLaunched = "Lending_RepeatWBankDetailScreenLaunched"
    const val Lending_RepeatWBankDetailScreenClicked = "Lending_RepeatWBankDetailScreenClicked"
    const val Lending_RepeatWBankDetailScreenBSShown = "Lending_RepeatWBankDetailScreenBSShown"
    const val Lending_RepeatWBankDetailScreenBSClicked = "Lending_RepeatWBankDetailScreenBSClicked"
    const val Lending_RepeatWBankDetailScreenNeedHelpClicked =
        "Lending_RepeatWBankDetailScreenNeedHelpClicked"
    const val Lending_SummaryScreenNeedHelpClicked = "Lending_SummaryScreenNeedHelpClicked"
    const val Lending_SummaryScreenBackClicked = "Lending_SummaryScreenBackClicked"
    const val Lending_LoanApplicationSuccessfulScreenLaunched =
        "Lending_LoanApplicationSuccessfulScreenLaunched"
    const val Lending_RejectionScreenShown = "Lending_RejectionScreenShown"
    const val Lending_RejectionScreenClicked = "Lending_RejectionScreenClicked"
    const val Lending_ApplicationPendingScreenShown = "Lending_ApplicationPendingScreenShown"
    const val Lending_ApplicationBankErrorScreenShown = "Lending_ApplicationBankErrorScreenShown"
    const val Lending_ApplicationPendingScreenClicked = "Lending_ApplicationPendingScreenClicked"
    const val Lending_ApplicationTimeOutScreenShown = "Lending_ApplicationTimeOutScreenShown"
    const val Lending_ApplicationTimeOutScreenClicked = "Lending_ApplicationTimeOutScreenClicked"
    const val Lending_YourLoanApprovedScreenClicked = "Lending_YourLoanApprovedScreenClicked"
    const val Lending_RepeatWBackButtonClicked = "Lending_RepeatWBackButtonClicked"
    const val LENDING_EXPERIMENT_TYPE = "LENDING_EXPERIMENT_TYPE"

    //Repayment Phase2
    const val Repay_EMIDetailsScreenLaunched = "Repay_EMIDetailsScreenLaunched"
    const val Repay_EMITransactionsClicked = "Repay_EMITransactionsClicked"
    const val Repay_EMITransactionDetailsScreenLaunched =
        "Repay_EMITransactionDetailsScreenLaunched"
    const val Repay_EMITransactionDetailsScreenClicked = "Repay_EMITransactionDetailsScreenClicked"


    const val Lending_PDetailsGetReadyCashClicked = "Lending_PDetailsGetReadyCashClicked"
    const val Lending_PDetailsFAQClicked = "Lending_PDetailsFAQClicked"
    const val Lending_EntryFieldSelected = "lending_entryfieldselected"
    const val Lending_BankDetailsIFSC = "lending_bankdetailsifsc"
    const val Lending_BankDetailsConfirmAccountNumber = "lending_bankdetailsconfirmaccountnumber"


    const val PDETAILS_FIRST_SCREEN = "Pdetails_first_screen"
    const val PDETAILS_MAIN_SCREEN = "Pdetails_main_screen"
    const val CAMERA_PREVIEW_SCREEN = "CAMERA_PREVIEW_SCREEN"
    const val CAMERA_CROP_SCREEN = "CAMERA_CROP_SCREEN"
    const val FETCHING_PAN_DETAILS_SCREEN = "fetching_pan_details_screen"
    const val PAN_CARD_FETCHED_SCREEN = "pan_card_fetched_screen"
    const val PAN_CREDIT_REPORT_NOTFOUND_SCREEN = "pan_credit_report_notfound_screen"
    const val PAN_MANUAL_ENTRY_SCREEN = "pan_manual_entry_screen"
    const val RCASH_ELIGIBILTY_SCREEN = "rcash_eligibilty_screen"
    const val READY_CASH_AMOUNT_SCREEN = "ready_cash_amount_screen"
    const val READY_CASH_EMI_SCREEN = "ready_cash_emi_screen"
    const val CHECKING_CKYC_RECORDS_SCREEN = "checking_cKYC_records_screen"
    const val EKYC_RECORDS_SHOWN_SCREEN = "eKYC_records_shown_screen"
    const val AADHAR_MANUAL_ENTRY_SCREEN = "aadhar_manual_entry_screen"
    const val AADHAR_MANUAL_VERIFYING_SCREEN = "aadhar_manual_verifying_screen"
    const val AADHAR_SENDING_OTP_SCREEN = "aadhar_sending_otp_screen"
    const val AADHAR_VERIFIICATION_SUCCESS_SCREEN = "aadhar_verifiication_success_screen"
    const val AADHAR_OCR_FIRST_SCREEN = "aadhar_OCR_first_screen"

    //    const val AADHAR_OCR_CROP_SCREEN = "aadhar_OCR_crop_screen"
    const val AADHAR_OCR_FILE_LARGE_SCREEN = "aadhar_OCR_file_large_screen"
    const val AADHAR_OCR_UPLOAD_FAILED_SCREEN = "aadhar_OCR_upload_failed_screen"
    const val AADHAR_ERROR_SCREEN = "aadhar_error_screen"
    const val AADHAR_OCR_UPLOADING_SCREEN = "aadhar_OCR_uploading_screen"
    const val AADHAR_OCR_FETCHING_DETAILS_SCREEN = "aadhar_OCR_fetching_details_screen"
    const val AADHAR_OCR_CONFIRM_SCREEN = "aadhar_OCR_confirm_screen"
    const val AADHAR_OCR_CAPTCHA_SCREEN = "aadhar_OCR_captcha_screen"
    const val SELFIE_LAUNCH_SCREEN = "selfie_launch_screen"

    //    const val SELFIE_CAMERA_SCREEN = "selfie_camera_screen"
//    const val SELFIE_PREVIEW_SCREEN = "selfie_preview_screen"
    const val SELFIE_SUCCESS_SCREEN = "selfie_success_screen"
    const val AADHAR_SERVER_DOWN_SCREEN = "aadhar_server_down_screen"
    const val KYC_VERIFICATION_SUCCESS_SCREEN = "KYC_verification_success_screen"
    const val NO_MOBILE_LINKED_SCREEN = "no_mobile_linked_screen"
    const val BANK_DETAILS_LAUNCH_SCREEN = "bank_details_launch_screen"
    const val BANK_ACCOUNTS_SHOWN_SCREEN = "bank_accounts_shown_screen"
    const val MANDATE_FAILURE_SCREEN = "mandate_failure_screen"
    const val BANK_DETAILS_REVIEW_SCREEN = "bank_details_review_screen"
    const val PENNYDROP_VERIFICATION_SCREEN = "pennydrop_verification_screen"
    const val BANK_VERIFICATION_FAILED_SCREEN = "bank_verification_failed_screen"
    const val RCASH_SUMMARY_SCREEN = "rcash_summary_screen"
    const val RCASH_SUMMARY_SETUP_EMI_SCREEN = "rcash_summary_setup_emi_screen"
    const val VERIFYING_MANDATE_SETUP_SCREEN = "verifying_mandate_setup_screen"
    const val EMI_SETUP_SUCCESS_SCREEN = "emi_setup_success_screen"
    const val LOAN_AGREEMENT_SCREEN = "loan_agreement_screen"
    const val CONFIRM_CKYC_SCREEN = "confirm_ckyc_screen"

    //    const val LOAN_AGREEMENT_OTP_SCREEN = "loan_agreement_otp_screen"
//    const val LOAN_EMAIL_VERIFICATION_SCREEN = "Loan_email_verification_screen"
    const val LOAN_APPLICATION_SUCCESS_SCREEN = "loan_application_success_screen"
    const val LOAN_APPLICATION_FAILURE_SCREEN = "loan_application_failure_screen"
    const val NAME_YOUR_READY_CASH_SCREEN = "name_your_ready_cash_screen"
    const val LOAN_ALL_SET_SCREEN = "loan_all_set_screen"
    const val LOAN_APPROVED_SCREEN = "loan_approved_screen"
    const val AMOUNT_AND_SEEKBAR_BOTH = "AMOUNT_AND_SEEKBAR_BOTH"
    const val AMOUNT_SELECTION_SEEKBAR = "AMOUNT_SELECTION_SEEKBAR"
    const val AMOUNT_SELECTION_INPUT_FIELD = "AMOUNT_SELECTION_INPUT_FIELD"
    const val NO_SELECTION_OF_FIELD = "NO_SELECTION_OF_FIELD"

    const val IFSC_CODE_TYPED = "IFSC_code_typed"
    const val ACCOUNT_NUMBER_TYPED = "account_number_typed"
    const val CONFIRM_ACCOUNT_NUMBER_TYPED = "confirm_account_number_typed"

    const val RLENDING_INITIAL_FLOW = "Rlending_InitialFlow"
    const val RLENDING_AFTERBANKSTATEMENTUPLOADFLOW = "RLending_AfterBankStatementUploadFlow"
    const val RLENDING_ERRORSCREENEVENT = "RLending_ErrorScreenEvent"

    const val RLENDING_CREDIT_SCORE = "RLending_credit_score"
    const val RLENDING_INSTANT_CASH = "RLending_instant_cash"

    const val FETCHING_CREDIT_SCORE_SCREEN = "fetching_credit_score_screen"
    const val CREDIT_SCORE_LANDING_SCREEN = "credit_score_landing_screen"
    const val INSTANT_CASH_LANDING_SCREEN = "instant_cash_landing_screen"
    const val BANK_STATEMENT_SCREEN = "bank_statement_screen"
    const val ENTER_DETAILS_BS = "enter_details_BS"
    const val BANK_DETAILS_SCREEN = "bank_details_screen"
    const val MOBILE_SCREEN = "mobile_screen"
    const val BANK_STATEMENT_CONFIRMATION_SCREEN = "BankStatement_confirmation_screen"
    const val UPLOAD_BANKSTATEMENT_SCREEN = "UPLOAD_BANKSTATEMENT_SCREEN"
    const val BANK_STATEMENT_VIEW_SCREEN = "BankStatement_view_screen"
    const val ENTER_PASSWORD_BS = "enter_password_BS"
    const val FINDING_OFFER_SCREEN = "finding_offer_screen"
    const val APPROVAL_FAILED_SCREEN = "approval_failed_screen"
    const val OFFER_APPROVED_SCREEN = "offer_approved_screen"

    const val FETCHING_CREDIT_SCREEN_LOADING = "fetching_credit_screen_loading"
    const val CREDIT_SCORE_LANDING_SCREEN_SHOWN = "credit_score_landing_screen_shown"
    const val CONTACT_SUPPORT_CLICKED = "contact_support_clicked"
    const val BACK_BUTTON_CLICKED = "BACK_BUTTON_CLICKED"
    const val CREDIT_SCORE_SCREEN_SCROLLED = "CREDIT_SCORE_SCREEN_SCROLLED"
    const val REFRESH_MY_SCORE_CLICKED = "REFRESH_MY_SCORE_CLICKED"
    const val ENTER_DETAILSBS_SHOWN = "enter_detailsbs_shown"
    const val BS_CROSS_BUTTON_CLICKED = "BS_cross_button_clicked"
    const val NAME_TYPED = "name_typed"
    const val PAN_TYPED = "PAN_typed"
    const val ENTER_DETAILSBS_SUBMIT_CLICKED = "enter_detailsBS_submit_clicked"
    const val CREDIT_SCORE_FAQ_CLICKED = "credit_score_FAQ_clicked"
    const val CREDIT_SCORE_GETSTARTED_CLICKED = "credit_score_getStarted_clicked"
    const val INSTANT_CASH_LANDING_SCREEN_SHOWN = "instant_cash_landing_screen_shown"
    const val INSTANT_CASH_FAQ_CLICKED = "instant_cash_FAQ_clicked"
    const val INSTANT_CASH_GETSTARTED_CLICKED = "instant_cash_getStarted_clicked"
    const val BANKSTATEMENT_CONFIRMATION_SCREEN_LAUNCHED =
        "BankStatement_confirmation_screen_launched"
    const val FILE_DELETED = "file_deleted"
    const val UPLOAD_MORE_CLICKED = "upload_more_clicked"
    const val BANKSTATEMENT_CONFIRM_CLICKED = "BankStatement_confirm_clicked"
    const val UPLOADING_BANKSTATEMENT_SCREEN_SHOWN = "uploading_BankStatement_screen_shown"
    const val UPLOAD_COMPLETED_SCREEN_SHOWN = "upload_completed_screen_shown"
    const val BANKSTATEMENT_VIEW_SCREEN_SHOWN = "BankStatement_view_screen_shown"
    const val BANKSTATEMENT_VIEW_SUBMIT_CLICKED = "BankStatement_view_submit_clicked"
    const val BANKSTATEMENT_VIEW_REUPLOAD_CLICKED = "BankStatement_view_reupload_clicked"
    const val ENTER_PASSWORD_BS_LAUNCHED = "enter_password_BS_launched"
    const val PASSWORD_ENTERED = "password_entered"
    const val PASSWORDBS_SUBMIT_CLICKED = "passwordBS_submit_clicked"
    const val PASSWORDBS_CROSS_BUTTON_CLICKED = "passwordBS_cross_button_clicked"
    const val FINDING_OFFER_SCREEN_LAUNCHED = "finding_offer_screen_launched"
    const val GO_TO_HOMESCREEN_CLICKED = "go_to_homescreen_clicked"
    const val APPROVAL_FAILED_SCREEN_SHOWN = "approval_failed_screen_shown"
    const val DETAIL_CREDIT_REPORT_CLICKED = "detail_credit_report_clicked"
    const val APPROVALFAILED_CROSS_BUTTON_CLICKED = "approvalFailed_cross_button_clicked"
    const val OFFER_APPROVED_SCREEN_SHOWN = "offer_approved_screen_shown"
    const val CHECK_YOUR_OFFER_CLICKED = "check_your_offer_clicked"


    const val BANK_DETAILS_SCREEN_LAUNCHED = "bank_details_screen_launched"

    //  const val ACCOUNT_NUMBER_TYPED  = "account_number_typed"
    const val IFSC_TYPED = "IFSC_typed"
    const val BANK_DETAILS_CONTINUE_CLICKED = "bank_details_continue_clicked"
    const val BANK_STATEMENT_SCREEN_LAUNCHED = "bank_statement_screen_launched"
    const val UPLOAD_BANK_STATEMENT_CLICKED = "upload_bank_statement_clicked"
    const val DEVICE_FILE_MANAGER_OPENED = "device_file_manager_opened"
    const val FILES_SELECTED = "files_selected"
    const val FILES_UPLOADED = "files_uploaded"
    const val CREDIT_STATUS = "credit_status"
    const val FOUND = "found"
    const val NOT_FOUND = "not_found"
    const val CREDIT_SCORE = "credit_status"
    const val error_message_failed_to_upload = "Some files failed to upload retry again."
    const val max_file = "You can upload a maximum of 6 pdfs files"
    const val KYC_SCREEN = "kyc_screen"
    const val NEED_HELP_CLICKED = "need_help_clicked"
    const val CreditReport_CreditScoreScreenLaunched = "CreditReport_CreditScoreScreenLaunched"
    const val CreditReport_DetailedReportScreenLaunched = "CreditReport_DetailedReportScreenLaunched"
    const val CreditReport_BackButtonClicked = "CreditReport_BackButtonClicked"
    const val CreditReport_NeedHelpClicked = "CreditReport_NeedHelpClicked"
    const val credit_score_status = "credit_score_status"
    const val credit_score =  "credit_score"
    const val credit_score_text =  "credit_score_text"
    const val detailed_credit_report_clicked =  "detailed_credit_report_clicked"
    const val get_credit_score_clicked =  "get_credit_score_clicked"
    const val go_to_homescreen_clicked =  "go_to_homescreen_clicked"
    const val check_credit_score_screen =  "check_credit_score_screen"
    const val credit_score_not_found_screen =  "credit_score_not_found_screen"
    const val credit_report_main_screen =  "credit_report_main_screen"
    const val credit_card_tab_shown =  "credit_card_tab_shown"
    const val loan_account_tab_shown =  "loan_account_tab_shown"
    const val credit_card_tab_clicked =  "credit_card_tab_clicked"
    const val loan_account_tab_clicked =  "loan_account_tab_clicked"
    const val monthly_repayments_value =  "monthly_repayments_value"
    const val credit_limit_usage_value =  "credit_limit_usage_value"
    const val report_update_avaliable =  "report_update_avaliable"
    const val credit_card_count =  "credit_card_count"
    const val loan_account_count =  "loan_account_count"
    const val total_account_count =  "total_account_count"
    const val active_credit_card_count =  "active_credit_card_count"
    const val active_loan_account_count =  "active_loan_account_count"
    const val closed_credit_card_count =  "closed_credit_card_count"
    const val closed_loan_account_count =  "closed_loan_account_count"
    const val total_active_account_count =  "total_active_account_count"
    const val check_now_clicked =  "check_now_clicked"
    const val details_bs_shown =  "details_bs_shown"
    const val details_bs_closed =  "details_bs_closed"
    const val details_bs_name_entered =  "details_bs_name_entered"
    const val details_bs_pan_entered =  "details_bs_pan_entered"
    const val details_bs_submit_clicked =  "details_bs_submit_clicked"
    const val delay_in_api_call =  "delay_in_api_call"

    //mandate revamp
    const val Lending_MandateApplicationPendingShown ="Lending_MandateApplicationPendingShown"
    const val Lending_MandateFailureScreen ="Lending_MandateFailureScreen"
    const val net_banking ="net_banking"
    const val debit_card ="debit_card"
    const val failure_title ="failure_title"
    const val failure_message ="failure_message"
    const val net_banking_disable_message ="net_banking_disable_message"
    const val debit_card_disable_message ="debit_card_disable_message"
    const val mandate_failure_screen ="mandate_failure_screen"
    const val net_banking_clicked ="net_banking_clicked"
    const val debit_card_clicked ="debit_card_clicked"

    //#################     EMI CALCULATOR      ############
    const val EmiCalculator_MainScreenLaunched = "EmiCalculator_MainScreenLaunched"
    const val EmiCalculator_BackButtonClicked = "EmiCalculator_BackButtonClicked"
    const val EmiCalculator_NeedHelpClicked = "EmiCalculator_NeedHelpClicked"

    //Keys
    const val type="type"
    const val interest = "interest"
    const val monthly_emi="monthly_emi"
    const val tenure_type="tenure_type"


    //Values
    const val loading_screen_shown = "loading_screen_shown"
    const val calculator_screen_shown = "calculator_screen_shown"
    const val launching_soon_screen_shown = "launching_soon_screen_shown"
    const val amount_changed = "amount_changed"
    const val interest_changed = "interest_changed"
    const val tenure_changed = "tenure_changed"
    const val tenure_type_changed = "tenure_type_changed"
    const val calculator_screen_updated = "calculator_screen_updated"
    const val get_instant_loan_clicked = "get_instant_loan_clicked"
    const val go_back_clicked = "go_back_clicked"
    const val calculator_screen = "calculator_screen"
    const val launching_soon_screen = "launching_soon_screen"
    const val month = "month"
    const val year = "year"
}