package com.jar.app.feature_buy_gold_v2.shared.util

object BuyGoldV2EventKey {

    //Props
    const val Experiment = "Experiment"
    const val Zomato = "Zomato"
    const val isNewBuyGoldFlow = "is_new_buy_gold_flow"
    const val Buy_Gold_YES = "yes"
    const val Buy_Gold_NO = "no"
    const val entryType = "entry_type"
    const val popularAmount = "popular_amount"
    const val allSuggestedValues = "all_suggested_values"
    const val preSelectedAmount = "pre_selected_amount"
    const val couponTitle = "coupon_title"
    const val couponCode = "coupon_code"
    const val POSITION = "position"
    const val isUserWinningsApplied = "is_user_winnings_applied"
    const val clickType = "click_type"
    const val yayButton = "yay_button"
    const val cancelButton = "cancel_button"
    const val isSuggestionClicked = "is_suggestion_clicked"
    const val couponOrder = "coupon_order"
    const val goldWeight = "gold_weight"
    const val Amount = "Amount"
    const val Quantity = "Quantity"
    const val Winnings = "Winnings"
    const val CouponCode = "CouponCode"
    const val CouponStatus = "coupon_status"
    const val CouponApplied = "coupon_applied"
    const val IsPopularAmountSelected = "is_popular_amount_selected"
    const val IsRecommendedAmountSelected = "is_recommended_amount_selected"
    const val ErrorMessage = "errorMessage"
    const val ErrorCode = "errorCode"
    const val PreviousPrice = "Previous Price"
    const val NewPrice = "New Price"
    const val IsAuspicious = "isAuspicious"
    const val Flow = "Flow"
    const val ApiType = "ApiType"
    const val State = "State"
    const val From = "From"
    const val FromScreen = "from_screen"
    const val isWinningsCoupon = "is_winnings_coupon"
    const val couponDiscountPercentage = "coupon_discount_percentage"
    const val moneySavedByCoupon = "money_saved_by_coupon"
    const val isPopupTyped = "is_popup_types"
    const val isGoldPriceDropped = "is_gold_price_dropped"
    const val jarWinningsCouponPosition = "jar_winnings_coupon_position"
    const val weeklymagicmessageshown = "weeklymagicmessageshown"
    const val Best_Offer_Coupon_Title = "Best_Offer_Coupon_Title"
    const val Coupon_Title = "Coupon_Title"
    const val Screen = "Screen"
    const val Coupon_Title_Typed = "Coupon_Title_Typed"
    const val Best_Offer_Coupon_Status = "Best_Offer_Coupon_Status"
    const val Coupon_Applied = "Coupon_Applied"
    const val Banner_Title = "Banner_Title"
    const val Winnings_Status = "Winnings_Status"
    const val auto_select_payment = "auto_select_payment"
    const val recommended_upi = "recommended_upi"
    const val True = "True"
    const val False = "False"
    const val available_upi = "available_upi"
    const val selected_upi = "selected_upi"
    const val Buy_Now = "Buy_Now"
    const val Cross = "Cross"
    const val Click_action = "Click_action"

    //Events
    const val BuyGoldScreen_FlowContext = "BuyGoldScreen_FlowContext"
    const val BuyGoldScreen_ApiFailed = "BuyGoldScreen_ApiFailed"
    const val BuyGold_IsAuspiciousFetched = "BuyGold_IsAuspiciousFetched"
    const val BuyNow_CouponPopupShown = "BuyNow_CouponPopupShown"
    const val SinglePageHomeScreenFlow = "SinglePageHomeFeed"
    const val BuyNow_CouponPopupClicked = "BuyNow_CouponPopupClicked"
    const val Shown_BuyGoldScreen = "Shown_BuyGoldScreen"
    const val Shown_BuyGoldScreenBanner = "Shown_BuyGoldScreenBanner"
    const val Shown_BuyGoldScreen_Ts = "Shown_BuyGoldScreen_Ts"
    const val BuyNow_GoldMoneyEntered = "BuyNow_GoldMoneyEntered"
    const val BuyNow_GoldWeightEntered = "BuyNow_GoldWeightEntered"
    const val Clicked_BackButton_BuyGoldScreen = "Clicked_BackButton_BuyGoldScreen"
    const val Clicked_BuyInRs_BuyGoldScreen = "Clicked_BuyInRs_BuyGoldScreen"
    const val Clicked_BuyInGms_BuyGoldScreen = "Clicked_BuyInGms_BuyGoldScreen"
    const val BuyNow_DiffCouponBSCancelClicked = "BuyNow_DiffCouponBSCancelClicked"
    const val Clicked_ShowBreakdown_BuyGoldScreen = "Clicked_ShowBreakdown_BuyGoldScreen"
    const val Clicked_ShubhMuhurat_BuyGoldScreen = "Clicked_ShubhMuhurat_BuyGoldScreen"
    const val Shown_ErrorMessage_BuyGoldScreen = "Shown_ErrorMessage_BuyGoldScreen"
    const val Shown_PriceChangeToast_BuyGoldScreen = "Shown_PriceChangeToast_BuyGoldScreen"
    const val Clicked_DifferentCoupon_OrderPreviewScreen = "Clicked_DifferentCoupon_OrderPreviewScreen"
    const val Clicked_PayNow_OrderPreviewScreen = "Clicked_PayNow_OrderPreviewScreen"
    const val ClickedApply_CouponTextbox_OrderPreviewScreen = "ClickedApply_CouponTextbox_OrderPreviewScreen"
    const val CouponCodeApplied_BuyGoldScreen = "CouponCodeApplied_BuyGoldScreen"
    const val Shown_ErrorMessage_OrderPreviewScreen = "Shown_ErrorMessage_OrderPreviewScreen"
    const val Shown_OrderSuccessScreen = "Shown_OrderSuccessScreen"
    const val Clicked_BackButton_OrderSuccessScreen = "Clicked_BackButton_OrderSuccessScreen"
    const val Clicked_ViewInvoice_OrderSuccessScreen = "Clicked_ViewInvoice_OrderSuccessScreen"
    const val Clicked_ShareButton_OrderSuccessScreen = "Clicked_ShareButton_OrderSuccessScreen"
    const val Shown_OrderFailureScreen = "Shown_OrderFailureScreen"
    const val Clicked_BackButton_OrderFailureScreen = "Clicked_BackButton_OrderFailureScreen"
    const val Clicked_ContactUs_OrderFailureScreen = "Clicked_ContactUs_OrderFailureScreen"
    const val Shown_OrderProcessingScreen = "Shown_OrderProcessingScreen"
    const val Clicked_TryAgain_OrderFailureScreen = "Clicked_TryAgain_OrderFailureScreen"
    const val Clicked_BackButton_OrderProcessingScreen = "Clicked_BackButton_OrderProcessingScreen"
    const val Clicked_CheckStatus_OrderProcessingScreen = "Clicked_CheckStatus_OrderProcessingScreen"
    const val Clicked_ContactUs_OrderProcessingScreen = "Clicked_ContactUs_OrderProcessingScreen"
    const val Clicked_Refresh_OrderProcessingScreen = "Clicked_Refresh_OrderProcessingScreen"
    const val Clicked_TryAgain_OrderProcessingScreen = "Clicked_TryAgain_OrderProcessingScreen"
    const val Shown_ShubhMuhurat_banner_BuyGoldScreen = "Shown_ShubhMuhurat_banner_BuyGoldScreen"
    const val Shown_price_drop_banner_BuyGoldScreen = "Shown_price_drop_banner_BuyGoldScreen"
    const val BuyGold_AmountBSLaunched = "BuyGold_AmountBSLaunched"
    const val BuyGold_AmountBSClicked = "BuyGold_AmountBSClicked"
    const val BuyGoldScreen_AllCoupons_Shown = "BuyGoldScreen_AllCoupons_Shown"
    const val BuyGoldScreen_ContextBanner_Clicked = "BuyGoldScreen_ContextBanner_Clicked"
    const val BannerType = "BannerType"

    const val Shown_PostOrder_CrossSellBanner = "Shown_PostOrder_CrossSellBanner"
    const val Clicked_PostOrder_CrossSellBanner = "Clicked_PostOrder_CrossSellBanner"
    const val BuyGold_AutoPayMethod_Click = "BuyGold_AutoPayMethod_Click"
    const val BuyGold_AutoPayMethod_BSShown = "BuyGold_AutoPayMethod_BSShown"
    const val BuyGold_AutoPayMethod_BSClick = "BuyGold_AutoPayMethod_BSClick"


    const val BuyGoldScreen_SkipClicked = "BuyGoldScreen_SkipClicked"
    const val BuyGold_AbandonScreenShown = "BuyGold_AbandonScreenShown"
    const val BuyGold_AbandonScreenClicked = "BuyGold_AbandonScreenClicked"
}

enum class ScreenName{
    Buy_Gold_Home_Screen,
    Buy_Gold_Coupons_Screen,
    Buy_Gold_Break_Down_Screen
}